--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "BANKAPP"."ACCTYPE" (
		"ACCTYPEID" NUMBER(10 , 0) NOT NULL,
		"ACCTYPE" VARCHAR2(45) NOT NULL,
		"MINAMT" FLOAT(126) NOT NULL,
		"INTERESTRATE" FLOAT(126) NOT NULL,
		"DESCRIPTION" CLOB
	);

CREATE TABLE "BANKAPP"."COMPLAINT" (
		"COMPNO" NUMBER(10 , 0) NOT NULL,
		"COMPTO" VARCHAR2(45) NOT NULL,
		"COMPFROM" VARCHAR2(45) NOT NULL,
		"SUBJECT" VARCHAR2(45) NOT NULL,
		"COMPMATTER" CLOB NOT NULL,
		"COMPDATE" DATE NOT NULL
	);

CREATE TABLE "BANKAPP"."LOGIN" (
		"LOGINID" NUMBER(10 , 0) NOT NULL,
		"USERNAME" VARCHAR2(45) NOT NULL,
		"PASSWORD" VARCHAR2(45) NOT NULL,
		"ANSWER" VARCHAR2(45) NOT NULL,
		"USERTYPE" VARCHAR2(45),
		"QUESTION" VARCHAR2(100) NOT NULL
	);

CREATE TABLE "BANKAPP"."ACCOUNT" (
		"ACCNUM" NUMBER(10 , 0) NOT NULL,
		"ACCTYPEID" NUMBER(10 , 0) NOT NULL,
		"ACCSTATUSID" NUMBER(10 , 0) NOT NULL,
		"CURRBAL" FLOAT(126),
		"OLDBAL" FLOAT(126),
		"CREATEDON" DATE NOT NULL,
		"LASTUPDATE" VARCHAR2(45)
	);

CREATE TABLE "BANKAPP"."LOAN" (
		"LOANID" NUMBER(10 , 0) NOT NULL,
		"CUSTID" NUMBER(10 , 0) NOT NULL,
		"ACCNUM" NUMBER(10 , 0) NOT NULL,
		"LOANTYPE" VARCHAR2(45) NOT NULL,
		"LOANDURATION" NUMBER(10 , 0) NOT NULL,
		"PROFESSION" VARCHAR2(45) NOT NULL,
		"INCOME" FLOAT(126) NOT NULL,
		"REQDATE" DATE NOT NULL,
		"STATUS" VARCHAR2(45) NOT NULL,
		"LOANCREATEDBY" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."LOADPAID" (
		"PAYMENTID" NUMBER(10 , 0) NOT NULL,
		"LOANID" NUMBER(10 , 0) NOT NULL,
		"INSTDUEAMT" FLOAT(126) NOT NULL,
		"INSTDUEDATE" DATE NOT NULL,
		"PAIDDATE" DATE NOT NULL,
		"PAIDAMT" FLOAT(126) NOT NULL,
		"NOINSTPAID" VARCHAR2(45) NOT NULL
	);

CREATE TABLE "BANKAPP"."TRANSACTION" (
		"TRANSID" NUMBER(10 , 0) NOT NULL,
		"TRANTYPE" VARCHAR2(45) NOT NULL,
		"TRANMETHOD" VARCHAR2(45) NOT NULL,
		"TRANDATE" DATE NOT NULL,
		"TRANAMT" FLOAT(126) NOT NULL,
		"CHEQUENUM" NUMBER(10 , 0),
		"ROUTINGNUM" VARCHAR2(45),
		"CUSTID" NUMBER(10 , 0) NOT NULL,
		"ACCNUM" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."LOANTYPE" (
		"LOANTYPE" VARCHAR2(45) NOT NULL,
		"MAXDURATION" NUMBER(10 , 0) NOT NULL,
		"MINDURATION" NUMBER(10 , 0) NOT NULL,
		"MAXAMT" FLOAT(126) NOT NULL,
		"MINAMT" FLOAT(126) NOT NULL
	);

CREATE TABLE "BANKAPP"."LOANAPPROVED" (
		"LOANAPPID" NUMBER(10 , 0) NOT NULL,
		"APPROVEDDATE" DATE NOT NULL,
		"APPROVEDBY" NUMBER(10 , 0) NOT NULL,
		"APPROVEDAMT" FLOAT(126) NOT NULL,
		"APPROVEREASON" CLOB NOT NULL,
		"LOANID" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."OVERDRAFT" (
		"ACCNUM" NUMBER(10 , 0) NOT NULL,
		"OVERDRAFTDATE" DATE NOT NULL,
		"OVERDRAFTAMT" FLOAT(126) NOT NULL
	);

CREATE TABLE "BANKAPP"."LOANREJECTED" (
		"LOANREJID" NUMBER(10 , 0) NOT NULL,
		"LOANREJDATE" DATE NOT NULL,
		"LOANREJBY" NUMBER(10 , 0) NOT NULL,
		"REJREASON" CLOB NOT NULL,
		"LOANID" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."CUSTOMER" (
		"CUSTID" NUMBER(10 , 0) NOT NULL,
		"FIRSTNAME" VARCHAR2(45) NOT NULL,
		"LASTNAME" VARCHAR2(45) NOT NULL,
		"AGE" NUMBER(10 , 0) NOT NULL,
		"DOB" DATE NOT NULL,
		"ADDRESS" VARCHAR2(45) NOT NULL,
		"CITY" VARCHAR2(45) NOT NULL,
		"STATE" VARCHAR2(45) NOT NULL,
		"COUNTRY" VARCHAR2(45) NOT NULL,
		"SEX" CHAR(6) NOT NULL,
		"PHONE" VARCHAR2(45),
		"EMAILID" VARCHAR2(60),
		"CREATEDBY" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."CUSTACC" (
		"CUSTID" NUMBER(10 , 0) NOT NULL,
		"ACCNUM" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."ACCSTATUS" (
		"ACCSTATUSID" NUMBER(10 , 0) NOT NULL,
		"ACCSTATUS" VARCHAR2(45) NOT NULL,
		"DESCRIPTION" CLOB
	);

CREATE TABLE "BANKAPP"."LOGINACC" (
		"LOGINID" NUMBER(10 , 0) NOT NULL,
		"ACCNUM" NUMBER(10 , 0) NOT NULL
	);

CREATE TABLE "BANKAPP"."EMPLOYEE" (
		"EMPID" NUMBER(10 , 0) NOT NULL,
		"EMPNAME" VARCHAR2(45) NOT NULL,
		"DESIGNATION" VARCHAR2(45) NOT NULL,
		"DEPARTMENT" VARCHAR2(45) NOT NULL
	);

CREATE INDEX "BANKAPP"."LOANIDFK_IDX" ON "BANKAPP"."LOANAPPROVED" ("LOANID" ASC);

CREATE INDEX "BANKAPP"."CUSTIDFK_IDX" ON "BANKAPP"."CUSTACC" ("CUSTID" ASC);

CREATE INDEX "BANKAPP"."TXCUSTIDFK_IDX" ON "BANKAPP"."TRANSACTION" ("CUSTID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_3" ON "BANKAPP"."COMPLAINT" ("COMPNO" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_11" ON "BANKAPP"."LOGIN" ("LOGINID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_7" ON "BANKAPP"."LOAN" ("LOANID" ASC, "CUSTID" ASC, "ACCNUM" ASC);

CREATE INDEX "BANKAPP"."ACCNUMFK2_IDX" ON "BANKAPP"."LOAN" ("ACCNUM" ASC);

CREATE INDEX "BANKAPP"."LOANTYPEFK3_IDX" ON "BANKAPP"."LOAN" ("LOANTYPE" ASC);

CREATE INDEX "BANKAPP"."LOANID_IDX" ON "BANKAPP"."LOANREJECTED" ("LOANID" ASC);

CREATE INDEX "BANKAPP"."ACCSTATUSIDFK_IDX" ON "BANKAPP"."ACCOUNT" ("ACCSTATUSID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY" ON "BANKAPP"."ACCSTATUS" ("ACCSTATUSID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_10" ON "BANKAPP"."LOANTYPE" ("LOANTYPE" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_6" ON "BANKAPP"."LOADPAID" ("PAYMENTID" ASC);

CREATE INDEX "BANKAPP"."ACCIDFK_IDX" ON "BANKAPP"."CUSTACC" ("ACCNUM" ASC);

CREATE INDEX "BANKAPP"."LOANID_IDX_1" ON "BANKAPP"."LOADPAID" ("LOANID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_13" ON "BANKAPP"."ACCTYPE" ("ACCTYPEID" ASC);

CREATE INDEX "BANKAPP"."LOGINFK_IDX" ON "BANKAPP"."LOGINACC" ("LOGINID" ASC);

CREATE INDEX "BANKAPP"."TXACTNUMFK_IDX" ON "BANKAPP"."TRANSACTION" ("ACCNUM" ASC);

CREATE INDEX "BANKAPP"."ACCTYPEIDFK_IDX" ON "BANKAPP"."ACCOUNT" ("ACCTYPEID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_5" ON "BANKAPP"."EMPLOYEE" ("EMPID" ASC);

CREATE INDEX "BANKAPP"."CUSTIDFK1_IDX" ON "BANKAPP"."LOAN" ("CUSTID" ASC);

CREATE INDEX "BANKAPP"."EMPFK_IDX" ON "BANKAPP"."LOAN" ("LOANCREATEDBY" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_2" ON "BANKAPP"."ACCOUNT" ("ACCNUM" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_1" ON "BANKAPP"."TRANSACTION" ("TRANSID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_4" ON "BANKAPP"."CUSTOMER" ("CUSTID" ASC);

CREATE INDEX "BANKAPP"."EMPID_IDX" ON "BANKAPP"."CUSTOMER" ("CREATEDBY" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_8" ON "BANKAPP"."LOANAPPROVED" ("LOANAPPID" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_12" ON "BANKAPP"."OVERDRAFT" ("ACCNUM" ASC);

CREATE UNIQUE INDEX "BANKAPP"."PRIMARY_9" ON "BANKAPP"."LOANREJECTED" ("LOANREJID" ASC);

CREATE INDEX "BANKAPP"."ACCNUMFK_IDX" ON "BANKAPP"."LOGINACC" ("ACCNUM" ASC);

CREATE UNIQUE INDEX "BANKAPP"."ACCSTATUS_UNIQUE" ON "BANKAPP"."ACCSTATUS" ("ACCSTATUS" ASC);

ALTER TABLE "BANKAPP"."ACCOUNT" ADD CONSTRAINT "PRIMARY_2" PRIMARY KEY ("ACCNUM");

ALTER TABLE "BANKAPP"."LOANTYPE" ADD CONSTRAINT "PRIMARY_10" PRIMARY KEY ("LOANTYPE");

ALTER TABLE "BANKAPP"."LOANREJECTED" ADD CONSTRAINT "PRIMARY_9" PRIMARY KEY ("LOANREJID");

ALTER TABLE "BANKAPP"."LOAN" ADD CONSTRAINT "PRIMARY_7" PRIMARY KEY ("LOANID", "CUSTID", "ACCNUM");

ALTER TABLE "BANKAPP"."ACCTYPE" ADD CONSTRAINT "PRIMARY_13" PRIMARY KEY ("ACCTYPEID");

ALTER TABLE "BANKAPP"."COMPLAINT" ADD CONSTRAINT "PRIMARY_3" PRIMARY KEY ("COMPNO");

ALTER TABLE "BANKAPP"."LOANAPPROVED" ADD CONSTRAINT "PRIMARY_8" PRIMARY KEY ("LOANAPPID");

ALTER TABLE "BANKAPP"."TRANSACTION" ADD CONSTRAINT "PRIMARY_1" PRIMARY KEY ("TRANSID");

ALTER TABLE "BANKAPP"."EMPLOYEE" ADD CONSTRAINT "PRIMARY_5" PRIMARY KEY ("EMPID");

ALTER TABLE "BANKAPP"."LOADPAID" ADD CONSTRAINT "PRIMARY_6" PRIMARY KEY ("PAYMENTID");

ALTER TABLE "BANKAPP"."CUSTOMER" ADD CONSTRAINT "PRIMARY_4" PRIMARY KEY ("CUSTID");

ALTER TABLE "BANKAPP"."OVERDRAFT" ADD CONSTRAINT "PRIMARY_12" PRIMARY KEY ("ACCNUM");

ALTER TABLE "BANKAPP"."LOGIN" ADD CONSTRAINT "PRIMARY_11" PRIMARY KEY ("LOGINID");

ALTER TABLE "BANKAPP"."ACCSTATUS" ADD CONSTRAINT "PRIMARY" PRIMARY KEY ("ACCSTATUSID");

ALTER TABLE "BANKAPP"."CUSTACC" ADD CONSTRAINT "ACCIDFK" FOREIGN KEY ("ACCNUM")
	REFERENCES "BANKAPP"."ACCOUNT" ("ACCNUM")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."ACCOUNT" ADD CONSTRAINT "ACCTYPEIDFK" FOREIGN KEY ("ACCTYPEID")
	REFERENCES "BANKAPP"."ACCTYPE" ("ACCTYPEID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."LOAN" ADD CONSTRAINT "EMPFK" FOREIGN KEY ("LOANCREATEDBY")
	REFERENCES "BANKAPP"."EMPLOYEE" ("EMPID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."CUSTACC" ADD CONSTRAINT "CUSTIDFK" FOREIGN KEY ("CUSTID")
	REFERENCES "BANKAPP"."CUSTOMER" ("CUSTID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."LOAN" ADD CONSTRAINT "CUSTIDFK1" FOREIGN KEY ("CUSTID")
	REFERENCES "BANKAPP"."CUSTOMER" ("CUSTID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."CUSTOMER" ADD CONSTRAINT "EMPID" FOREIGN KEY ("CREATEDBY")
	REFERENCES "BANKAPP"."EMPLOYEE" ("EMPID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."LOGINACC" ADD CONSTRAINT "LOGINFK" FOREIGN KEY ("LOGINID")
	REFERENCES "BANKAPP"."LOGIN" ("LOGINID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."TRANSACTION" ADD CONSTRAINT "TXACTNUMFK" FOREIGN KEY ("ACCNUM")
	REFERENCES "BANKAPP"."ACCOUNT" ("ACCNUM")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."ACCOUNT" ADD CONSTRAINT "ACCSTATUSIDFK" FOREIGN KEY ("ACCSTATUSID")
	REFERENCES "BANKAPP"."ACCSTATUS" ("ACCSTATUSID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."OVERDRAFT" ADD CONSTRAINT "OVERDRAFFK" FOREIGN KEY ("ACCNUM")
	REFERENCES "BANKAPP"."ACCOUNT" ("ACCNUM")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."LOGINACC" ADD CONSTRAINT "ACCNUMFK" FOREIGN KEY ("ACCNUM")
	REFERENCES "BANKAPP"."ACCOUNT" ("ACCNUM")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."TRANSACTION" ADD CONSTRAINT "TXCUSTIDFK" FOREIGN KEY ("CUSTID")
	REFERENCES "BANKAPP"."CUSTOMER" ("CUSTID")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."LOAN" ADD CONSTRAINT "ACCNUMFK2" FOREIGN KEY ("ACCNUM")
	REFERENCES "BANKAPP"."ACCOUNT" ("ACCNUM")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE "BANKAPP"."LOAN" ADD CONSTRAINT "LOANTYPEFK3" FOREIGN KEY ("LOANTYPE")
	REFERENCES "BANKAPP"."LOANTYPE" ("LOANTYPE")
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

