package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private long accnum;
	private Acctype acctype;
	private Accstatus accstatus;
	private Double currbal;
	private Double oldbal;
	private Date createdon;
	private String lastupdate;
	private Set loans = new HashSet(0);
	private Set transactions = new HashSet(0);
	private Set custaccs = new HashSet(0);
	private Overdraft overdraft;
	private Set loginaccs = new HashSet(0);

	public Account() {
	}

	public Account(long accnum, Acctype acctype, Accstatus accstatus,
			Date createdon) {
		this.accnum = accnum;
		this.acctype = acctype;
		this.accstatus = accstatus;
		this.createdon = createdon;
	}

	public Account(long accnum, Acctype acctype, Accstatus accstatus,
			Double currbal, Double oldbal, Date createdon, String lastupdate,
			Set loans, Set transactions, Set custaccs, Overdraft overdraft,
			Set loginaccs) {
		this.accnum = accnum;
		this.acctype = acctype;
		this.accstatus = accstatus;
		this.currbal = currbal;
		this.oldbal = oldbal;
		this.createdon = createdon;
		this.lastupdate = lastupdate;
		this.loans = loans;
		this.transactions = transactions;
		this.custaccs = custaccs;
		this.overdraft = overdraft;
		this.loginaccs = loginaccs;
	}

	public long getAccnum() {
		return this.accnum;
	}

	public void setAccnum(long accnum) {
		this.accnum = accnum;
	}

	public Acctype getAcctype() {
		return this.acctype;
	}

	public void setAcctype(Acctype acctype) {
		this.acctype = acctype;
	}

	public Accstatus getAccstatus() {
		return this.accstatus;
	}

	public void setAccstatus(Accstatus accstatus) {
		this.accstatus = accstatus;
	}

	public Double getCurrbal() {
		return this.currbal;
	}

	public void setCurrbal(Double currbal) {
		this.currbal = currbal;
	}

	public Double getOldbal() {
		return this.oldbal;
	}

	public void setOldbal(Double oldbal) {
		this.oldbal = oldbal;
	}

	public Date getCreatedon() {
		return this.createdon;
	}

	public void setCreatedon(Date createdon) {
		this.createdon = createdon;
	}

	public String getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(String lastupdate) {
		this.lastupdate = lastupdate;
	}

	public Set getLoans() {
		return this.loans;
	}

	public void setLoans(Set loans) {
		this.loans = loans;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

	public Set getCustaccs() {
		return this.custaccs;
	}

	public void setCustaccs(Set custaccs) {
		this.custaccs = custaccs;
	}

	public Overdraft getOverdraft() {
		return this.overdraft;
	}

	public void setOverdraft(Overdraft overdraft) {
		this.overdraft = overdraft;
	}

	public Set getLoginaccs() {
		return this.loginaccs;
	}

	public void setLoginaccs(Set loginaccs) {
		this.loginaccs = loginaccs;
	}

}
