package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Accstatus generated by hbm2java
 */
public class Accstatus implements java.io.Serializable {

	private long accstatusid;
	private String accstatus;
	private Clob description;
	private Set accounts = new HashSet(0);

	public Accstatus() {
	}

	public Accstatus(long accstatusid, String accstatus) {
		this.accstatusid = accstatusid;
		this.accstatus = accstatus;
	}

	public Accstatus(long accstatusid, String accstatus, Clob description,
			Set accounts) {
		this.accstatusid = accstatusid;
		this.accstatus = accstatus;
		this.description = description;
		this.accounts = accounts;
	}

	public long getAccstatusid() {
		return this.accstatusid;
	}

	public void setAccstatusid(long accstatusid) {
		this.accstatusid = accstatusid;
	}

	public String getAccstatus() {
		return this.accstatus;
	}

	public void setAccstatus(String accstatus) {
		this.accstatus = accstatus;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

}
