package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;

/**
 * Acctype generated by hbm2java
 */
public class Acctype implements java.io.Serializable {

	private long acctypeid;
	private String acctype;
	private double minamt;
	private double interestrate;
	private Clob description;
	private Set accounts = new HashSet(0);

	public Acctype() {
	}

	public Acctype(long acctypeid, String acctype, double minamt,
			double interestrate) {
		this.acctypeid = acctypeid;
		this.acctype = acctype;
		this.minamt = minamt;
		this.interestrate = interestrate;
	}

	public Acctype(long acctypeid, String acctype, double minamt,
			double interestrate, Clob description, Set accounts) {
		this.acctypeid = acctypeid;
		this.acctype = acctype;
		this.minamt = minamt;
		this.interestrate = interestrate;
		this.description = description;
		this.accounts = accounts;
	}

	public long getAcctypeid() {
		return this.acctypeid;
	}

	public void setAcctypeid(long acctypeid) {
		this.acctypeid = acctypeid;
	}

	public String getAcctype() {
		return this.acctype;
	}

	public void setAcctype(String acctype) {
		this.acctype = acctype;
	}

	public double getMinamt() {
		return this.minamt;
	}

	public void setMinamt(double minamt) {
		this.minamt = minamt;
	}

	public double getInterestrate() {
		return this.interestrate;
	}

	public void setInterestrate(double interestrate) {
		this.interestrate = interestrate;
	}

	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

}
