package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

/**
 * Custacc generated by hbm2java
 */
public class Custacc implements java.io.Serializable {

	private CustaccId id;
	private Customer customer;
	private Account account;

	public Custacc() {
	}

	public Custacc(CustaccId id, Customer customer, Account account) {
		this.id = id;
		this.customer = customer;
		this.account = account;
	}

	public CustaccId getId() {
		return this.id;
	}

	public void setId(CustaccId id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
