package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private long custid;
	private Employee employee;
	private String firstname;
	private String lastname;
	private long age;
	private Date dob;
	private String address;
	private String city;
	private String state;
	private String country;
	private String sex;
	private String phone;
	private String emailid;
	private Set loans = new HashSet(0);
	private Set transactions = new HashSet(0);
	private Set custaccs = new HashSet(0);

	public Customer() {
	}

	public Customer(long custid, Employee employee, String firstname,
			String lastname, long age, Date dob, String address, String city,
			String state, String country, String sex) {
		this.custid = custid;
		this.employee = employee;
		this.firstname = firstname;
		this.lastname = lastname;
		this.age = age;
		this.dob = dob;
		this.address = address;
		this.city = city;
		this.state = state;
		this.country = country;
		this.sex = sex;
	}

	public Customer(long custid, Employee employee, String firstname,
			String lastname, long age, Date dob, String address, String city,
			String state, String country, String sex, String phone,
			String emailid, Set loans, Set transactions, Set custaccs) {
		this.custid = custid;
		this.employee = employee;
		this.firstname = firstname;
		this.lastname = lastname;
		this.age = age;
		this.dob = dob;
		this.address = address;
		this.city = city;
		this.state = state;
		this.country = country;
		this.sex = sex;
		this.phone = phone;
		this.emailid = emailid;
		this.loans = loans;
		this.transactions = transactions;
		this.custaccs = custaccs;
	}

	public long getCustid() {
		return this.custid;
	}

	public void setCustid(long custid) {
		this.custid = custid;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public long getAge() {
		return this.age;
	}

	public void setAge(long age) {
		this.age = age;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public Set getLoans() {
		return this.loans;
	}

	public void setLoans(Set loans) {
		this.loans = loans;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

	public Set getCustaccs() {
		return this.custaccs;
	}

	public void setCustaccs(Set custaccs) {
		this.custaccs = custaccs;
	}

}
