package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private long empid;
	private String empname;
	private String designation;
	private String department;
	private Set customers = new HashSet(0);
	private Set loans = new HashSet(0);

	public Employee() {
	}

	public Employee(long empid, String empname, String designation,
			String department) {
		this.empid = empid;
		this.empname = empname;
		this.designation = designation;
		this.department = department;
	}

	public Employee(long empid, String empname, String designation,
			String department, Set customers, Set loans) {
		this.empid = empid;
		this.empname = empname;
		this.designation = designation;
		this.department = department;
		this.customers = customers;
		this.loans = loans;
	}

	public long getEmpid() {
		return this.empid;
	}

	public void setEmpid(long empid) {
		this.empid = empid;
	}

	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

	public Set getLoans() {
		return this.loans;
	}

	public void setLoans(Set loans) {
		this.loans = loans;
	}

}
