package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.sql.Clob;
import java.util.Date;

/**
 * Loanapproved generated by hbm2java
 */
public class Loanapproved implements java.io.Serializable {

	private long loanappid;
	private Date approveddate;
	private long approvedby;
	private double approvedamt;
	private Clob approvereason;
	private long loanid;

	public Loanapproved() {
	}

	public Loanapproved(long loanappid, Date approveddate, long approvedby,
			double approvedamt, Clob approvereason, long loanid) {
		this.loanappid = loanappid;
		this.approveddate = approveddate;
		this.approvedby = approvedby;
		this.approvedamt = approvedamt;
		this.approvereason = approvereason;
		this.loanid = loanid;
	}

	public long getLoanappid() {
		return this.loanappid;
	}

	public void setLoanappid(long loanappid) {
		this.loanappid = loanappid;
	}

	public Date getApproveddate() {
		return this.approveddate;
	}

	public void setApproveddate(Date approveddate) {
		this.approveddate = approveddate;
	}

	public long getApprovedby() {
		return this.approvedby;
	}

	public void setApprovedby(long approvedby) {
		this.approvedby = approvedby;
	}

	public double getApprovedamt() {
		return this.approvedamt;
	}

	public void setApprovedamt(double approvedamt) {
		this.approvedamt = approvedamt;
	}

	public Clob getApprovereason() {
		return this.approvereason;
	}

	public void setApprovereason(Clob approvereason) {
		this.approvereason = approvereason;
	}

	public long getLoanid() {
		return this.loanid;
	}

	public void setLoanid(long loanid) {
		this.loanid = loanid;
	}

}
