package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Loan generated by hbm2java
 */
public class Loan implements java.io.Serializable {

	private LoanId id;
	private Employee employee;
	private Customer customer;
	private Loantype loantype;
	private Account account;
	private long loanduration;
	private String profession;
	private double income;
	private Date reqdate;
	private String status;

	public Loan() {
	}

	public Loan(LoanId id, Employee employee, Customer customer,
			Loantype loantype, Account account, long loanduration,
			String profession, double income, Date reqdate, String status) {
		this.id = id;
		this.employee = employee;
		this.customer = customer;
		this.loantype = loantype;
		this.account = account;
		this.loanduration = loanduration;
		this.profession = profession;
		this.income = income;
		this.reqdate = reqdate;
		this.status = status;
	}

	public LoanId getId() {
		return this.id;
	}

	public void setId(LoanId id) {
		this.id = id;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Loantype getLoantype() {
		return this.loantype;
	}

	public void setLoantype(Loantype loantype) {
		this.loantype = loantype;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public long getLoanduration() {
		return this.loanduration;
	}

	public void setLoanduration(long loanduration) {
		this.loanduration = loanduration;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public double getIncome() {
		return this.income;
	}

	public void setIncome(double income) {
		this.income = income;
	}

	public Date getReqdate() {
		return this.reqdate;
	}

	public void setReqdate(Date reqdate) {
		this.reqdate = reqdate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
