package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Loantype generated by hbm2java
 */
public class Loantype implements java.io.Serializable {

	private String loantype;
	private long maxduration;
	private long minduration;
	private double maxamt;
	private double minamt;
	private Set loans = new HashSet(0);

	public Loantype() {
	}

	public Loantype(String loantype, long maxduration, long minduration,
			double maxamt, double minamt) {
		this.loantype = loantype;
		this.maxduration = maxduration;
		this.minduration = minduration;
		this.maxamt = maxamt;
		this.minamt = minamt;
	}

	public Loantype(String loantype, long maxduration, long minduration,
			double maxamt, double minamt, Set loans) {
		this.loantype = loantype;
		this.maxduration = maxduration;
		this.minduration = minduration;
		this.maxamt = maxamt;
		this.minamt = minamt;
		this.loans = loans;
	}

	public String getLoantype() {
		return this.loantype;
	}

	public void setLoantype(String loantype) {
		this.loantype = loantype;
	}

	public long getMaxduration() {
		return this.maxduration;
	}

	public void setMaxduration(long maxduration) {
		this.maxduration = maxduration;
	}

	public long getMinduration() {
		return this.minduration;
	}

	public void setMinduration(long minduration) {
		this.minduration = minduration;
	}

	public double getMaxamt() {
		return this.maxamt;
	}

	public void setMaxamt(double maxamt) {
		this.maxamt = maxamt;
	}

	public double getMinamt() {
		return this.minamt;
	}

	public void setMinamt(double minamt) {
		this.minamt = minamt;
	}

	public Set getLoans() {
		return this.loans;
	}

	public void setLoans(Set loans) {
		this.loans = loans;
	}

}
