package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

/**
 * LoginaccId generated by hbm2java
 */
public class LoginaccId implements java.io.Serializable {

	private long loginid;
	private long accnum;

	public LoginaccId() {
	}

	public LoginaccId(long loginid, long accnum) {
		this.loginid = loginid;
		this.accnum = accnum;
	}

	public long getLoginid() {
		return this.loginid;
	}

	public void setLoginid(long loginid) {
		this.loginid = loginid;
	}

	public long getAccnum() {
		return this.accnum;
	}

	public void setAccnum(long accnum) {
		this.accnum = accnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginaccId))
			return false;
		LoginaccId castOther = (LoginaccId) other;

		return (this.getLoginid() == castOther.getLoginid())
				&& (this.getAccnum() == castOther.getAccnum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLoginid();
		result = 37 * result + (int) this.getAccnum();
		return result;
	}

}
