package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Overdraft generated by hbm2java
 */
public class Overdraft implements java.io.Serializable {

	private long accnum;
	private Account account;
	private Date overdraftdate;
	private double overdraftamt;

	public Overdraft() {
	}

	public Overdraft(Account account, Date overdraftdate, double overdraftamt) {
		this.account = account;
		this.overdraftdate = overdraftdate;
		this.overdraftamt = overdraftamt;
	}

	public long getAccnum() {
		return this.accnum;
	}

	public void setAccnum(long accnum) {
		this.accnum = accnum;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Date getOverdraftdate() {
		return this.overdraftdate;
	}

	public void setOverdraftdate(Date overdraftdate) {
		this.overdraftdate = overdraftdate;
	}

	public double getOverdraftamt() {
		return this.overdraftamt;
	}

	public void setOverdraftamt(double overdraftamt) {
		this.overdraftamt = overdraftamt;
	}

}
