package com.bank.model;

// Generated Feb 27, 2016 9:42:37 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private long transid;
	private Customer customer;
	private Account account;
	private String trantype;
	private String tranmethod;
	private Date trandate;
	private double tranamt;
	private Long chequenum;
	private String routingnum;

	public Transaction() {
	}

	public Transaction(long transid, Customer customer, Account account,
			String trantype, String tranmethod, Date trandate, double tranamt) {
		this.transid = transid;
		this.customer = customer;
		this.account = account;
		this.trantype = trantype;
		this.tranmethod = tranmethod;
		this.trandate = trandate;
		this.tranamt = tranamt;
	}

	public Transaction(long transid, Customer customer, Account account,
			String trantype, String tranmethod, Date trandate, double tranamt,
			Long chequenum, String routingnum) {
		this.transid = transid;
		this.customer = customer;
		this.account = account;
		this.trantype = trantype;
		this.tranmethod = tranmethod;
		this.trandate = trandate;
		this.tranamt = tranamt;
		this.chequenum = chequenum;
		this.routingnum = routingnum;
	}

	public long getTransid() {
		return this.transid;
	}

	public void setTransid(long transid) {
		this.transid = transid;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getTrantype() {
		return this.trantype;
	}

	public void setTrantype(String trantype) {
		this.trantype = trantype;
	}

	public String getTranmethod() {
		return this.tranmethod;
	}

	public void setTranmethod(String tranmethod) {
		this.tranmethod = tranmethod;
	}

	public Date getTrandate() {
		return this.trandate;
	}

	public void setTrandate(Date trandate) {
		this.trandate = trandate;
	}

	public double getTranamt() {
		return this.tranamt;
	}

	public void setTranamt(double tranamt) {
		this.tranamt = tranamt;
	}

	public Long getChequenum() {
		return this.chequenum;
	}

	public void setChequenum(Long chequenum) {
		this.chequenum = chequenum;
	}

	public String getRoutingnum() {
		return this.routingnum;
	}

	public void setRoutingnum(String routingnum) {
		this.routingnum = routingnum;
	}

}
